// Blog posts — genuinely useful, fact-based buyer guides (NOT auto-generated fluff).
// Each post: slug, title, description, date (ISO), readMins, and body blocks.
// Body block types: 'p' (paragraph, may contain <strong>/<a>), 'h2', 'ul' (items[]),
// 'quote', 'table' (head[] + rows[][]).

export const posts = [
  {
    slug: 'nepal-duty-free-apparel-eu-uk-canada',
    title: 'How EU, UK & Canadian buyers save import duty sourcing garments from Nepal',
    description:
      'Nepal’s LDC status means knit garments enter the EU, UK, and Canada at 0% import duty under single-transformation rules — even with imported fabric. Here’s how it works, and the 2026 window to plan for.',
    date: '2026-07-13',
    readMins: 6,
    tags: ['Duty-free', 'Sourcing'],
    body: [
      { type: 'p', text: 'If you import knit garments — t-shirts, polos, jersey — into the EU, UK, or Canada, where you source them changes your landed cost before you’ve negotiated a single unit price. Sourcing from Nepal can mean <strong>0% import duty</strong>, versus the standard rate you’d pay from most countries. Here’s exactly why, and the timeline every buyer should understand.' },
      { type: 'h2', text: 'Why Nepal is duty-free (and China isn’t)' },
      { type: 'p', text: 'Nepal is classified as a Least Developed Country (LDC). Major economies grant LDCs preferential, usually zero, import duty to support their development — through the EU’s <strong>Everything But Arms (EBA)</strong> scheme, the UK’s <strong>Developing Countries Trading Scheme (DCTS)</strong>, and Canada’s <strong>Least Developed Country Tariff (LDCT)</strong>.' },
      { type: 'p', text: 'For a cotton knit t-shirt, the standard EU (MFN) import duty is roughly <strong>12%</strong>. From Nepal under EBA, it’s <strong>0%</strong>. The UK and Canada mirror that duty-free access for LDC-made garments.' },
      { type: 'h2', text: 'The key: “single transformation” means imported fabric still qualifies' },
      { type: 'p', text: 'A common misconception is that using imported (e.g. Chinese) fabric disqualifies the duty-free origin. For LDC garments, it does not. The EU, UK, and Canada apply <strong>single-transformation</strong> rules of origin: cutting and sewing the garment in Nepal is enough for it to count as Nepal-made. Canada’s rule (updated January 2025) is the most generous — a garment “cut, sewn, or knit” in an LDC qualifies even with foreign fabric.' },
      { type: 'p', text: 'In practice, the factory supplies a <strong>Certificate of Origin</strong> (via REX registration for the EU), and your goods clear at the preferential rate.' },
      { type: 'h2', text: 'What about the United States?' },
      { type: 'p', text: 'Be clear-eyed here: the US does <strong>not</strong> currently offer duty-free access for knit tees and polos from Nepal — US GSP has lapsed, and the Nepal Trade Preference Program expired at the end of 2025. However, Nepal carries roughly a <strong>10% US tariff</strong>, far below India (~50%) or Bangladesh (~20%). So for US importers, Nepal isn’t “duty-free” — it’s the <strong>lowest-tariff option in South Asia</strong>, and a smart way to de-risk sourcing.' },
      { type: 'table', head: ['Market', 'Scheme', 'Duty from Nepal'], rows: [
        ['EU', 'Everything But Arms (EBA)', '0%'],
        ['UK', 'DCTS', '0%'],
        ['Canada', 'LDCT', '0%'],
        ['USA', 'No scheme (lowest S. Asia tariff)', '~10%'],
      ] },
      { type: 'h2', text: 'The 2026 window — and why to plan now' },
      { type: 'p', text: 'Nepal is scheduled to graduate from LDC status in <strong>November 2026</strong>. The EU and UK grant a transition period keeping duty-free access to around <strong>2029</strong>. After that, access likely shifts to standard GSP with stricter “double transformation” rules — under which imported fabric may no longer qualify. Translation: there’s a real window to lock in duty-free sourcing now, and a good manufacturing partner will help you plan for the transition.' },
      { type: 'quote', text: 'Duty rates and rules of origin depend on your market and your product’s exact HS code, and LDC preferences change over time. Always confirm the current rule for your destination and product before you commit.' },
      { type: 'h2', text: 'The bottom line for buyers' },
      { type: 'p', text: 'If your market is the EU, UK, or Canada, sourcing knit basics from Nepal can remove ~12% of duty from your landed cost, legitimately and with proper documentation. If it’s the US, Nepal is the lowest-tariff South-Asian option. Either way, it’s worth a conversation. <a href="/why-nepal/">See our full duty-free breakdown</a>, or <a href="/contact/">tell us your market</a> and we’ll confirm exactly what applies to your program.' },
    ],
  },
  {
    slug: 'nepal-vs-bangladesh-vs-india-knit-basics',
    title: 'Nepal vs. Bangladesh vs. India for knit basics: a 2026 sourcing comparison',
    description:
      'A practical comparison for brands and importers choosing where to make t-shirts and polos in 2026 — on duty access, tariffs, MOQ, and supply-chain risk.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['Sourcing', 'China plus one'],
    body: [
      { type: 'p', text: 'With brands actively diversifying their apparel sourcing — over 80% of US fashion companies now source from 10+ countries, and most plan to add more — the question “where should we make our knit basics?” is live again. Here’s a practical, honest comparison of three South-Asian options for tees and polos.' },
      { type: 'h2', text: 'Duty access into your market' },
      { type: 'p', text: 'This is where Nepal stands out. As an LDC, Nepal enters the <strong>EU, UK, and Canada duty-free</strong> under single-transformation rules. India lost EU GSP benefits years ago and faces standard duties; Bangladesh, also an LDC, enjoys similar duty-free access but graduates from LDC status around the same window as Nepal. For US buyers, Nepal’s ~10% tariff is dramatically lower than India’s ~50% or Bangladesh’s ~20% in the current tariff environment.' },
      { type: 'h2', text: 'Scale vs. attention' },
      { type: 'p', text: 'Bangladesh and India are giants — enormous capacity, but their factories are built around large buyers and big minimums. Emerging and mid-size brands often struggle to get attention, low MOQs, or responsive communication. Nepal’s industry is smaller and less overbooked, which for the right buyer means <strong>dedicated capacity, lower minimums, and direct access</strong> to the people running your order.' },
      { type: 'h2', text: 'MOQ and small-batch friendliness' },
      { type: 'p', text: 'If you need 300–500 pieces per style to test a range, a mega-factory in Dhaka or Tiruppur is rarely the right fit. Smaller Nepali factories are structurally better suited to low-MOQ, multi-style programs — the reality for most growing brands.' },
      { type: 'h2', text: 'The honest trade-offs of Nepal' },
      { type: 'ul', items: [
        'Landlocked — bulk sea freight routes via Kolkata/Vizag, so plan realistic lead times.',
        'Smaller industry — fewer giant factories; best for small-to-mid programs, not 100k-piece single orders.',
        'Fabric is often imported (from China) — which is fine for duty-free under single transformation, but worth understanding.',
      ] },
      { type: 'h2', text: 'Who should consider Nepal' },
      { type: 'p', text: 'Nepal is a strong fit if you’re a brand, importer, or reseller selling into the EU/UK/Canada (duty-free) or the US (lowest S. Asia tariff), you value low MOQ and a responsive partner over raw scale, and you’re diversifying away from over-concentration in China, India, or Bangladesh.' },
      { type: 'p', text: 'That’s exactly the lane we work in — private-label knit basics, low MOQ, duty-free-savvy. <a href="/products/">See what we make</a> or <a href="/contact/">start a conversation</a>.' },
    ],
  },
  {
    slug: 'how-to-find-vet-overseas-clothing-manufacturer',
    title: 'How to find and vet an overseas clothing manufacturer (without getting scammed)',
    description:
      'A practical checklist for brands sourcing overseas: how to find a garment factory, spot scam red flags, verify a supplier, and structure payments so you’re protected.',
    date: '2026-07-13',
    readMins: 7,
    tags: ['Sourcing', 'Trust'],
    body: [
      { type: 'p', text: 'Sending money to a factory you’ve never met, in a country you may never have visited, is the scariest part of sourcing overseas — especially with a smaller or newer supplier. The good news: a few disciplined steps remove almost all of the risk. Here’s how experienced buyers find and vet manufacturers.' },
      { type: 'h2', text: 'Where to find manufacturers' },
      { type: 'ul', items: [
        'Sourcing marketplaces: Alibaba, Global Sources, Sewport, Maker’s Row, Fibre2Fashion.',
        'Trade bodies: national garment associations (e.g. Garment Association of Nepal) and export-promotion agencies list vetted members.',
        'Referrals: ask other brand owners — the highest-trust source of all.',
        'Search: "[product] manufacturer [country]" surfaces factories that invest in being findable.',
      ] },
      { type: 'h2', text: 'Scam red flags to walk away from' },
      { type: 'ul', items: [
        'Pressure for a large 100% upfront payment to a personal account.',
        'No physical address, no registered company, no export licence.',
        'Prices dramatically below everyone else (bait pricing).',
        'Refusal to provide a sample, a video call, or references.',
        'Only a WhatsApp number — no website, no verifiable identity.',
      ] },
      { type: 'h2', text: 'How to verify a supplier (the checklist)' },
      { type: 'ul', items: [
        'Confirm they’re a real registered exporter (business registration + EXIM/export code).',
        'Ask for a live video walkthrough of the factory floor and your goods on the line.',
        'Order a pre-production sample before any bulk commitment — judge fabric, fit, finish.',
        'Request references or named clients you can contact.',
        'Start with a smaller first order to build trust before scaling.',
      ] },
      { type: 'h2', text: 'Protect your money with the right payment terms' },
      { type: 'p', text: 'Never wire 100% upfront to a stranger. Use staged terms — e.g. a deposit to start, balance against inspection or shipping documents — or a Letter of Credit (L/C) for larger orders, which releases funds only when documented conditions are met. Structure payment so your money tracks real progress.' },
      { type: 'quote', text: 'The single best protection: approve a physical sample first, start small, and pay in stages tied to milestones. Scams rely on you skipping these — legitimate factories welcome them.' },
      { type: 'h2', text: 'How we make it easy to trust us' },
      { type: 'p', text: 'We’re a registered exporter with a physical factory in Gaindakot, Nepal — visit in person or ask for a live video tour any time. Nothing goes to bulk until you approve a sample, and we work on fair, staged payment terms. <a href="/why-nepal/">See our duty-free advantage</a> or <a href="/contact/">request a sample</a> — we’d rather earn your trust order by order than ask you to take it on faith.' },
    ],
  },
  {
    slug: 'low-moq-clothing-manufacturing-small-brands',
    title: 'Low-MOQ clothing manufacturing: how small brands make 300–500 pieces per style',
    description:
      'Most factories want 1,000+ pieces per style. Here’s how emerging brands find low-MOQ manufacturers, why minimums exist, and how to keep your first order small and affordable.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['Low MOQ', 'Startups'],
    body: [
      { type: 'p', text: 'If you’re launching or growing a clothing brand, the biggest wall you hit is the MOQ — the minimum order quantity a factory will run. Many demand 1,000+ pieces per style and colour, which is impossible cash-flow for a brand testing a range. Here’s how to work with low-MOQ manufacturers instead.' },
      { type: 'h2', text: 'Why MOQs exist' },
      { type: 'p', text: 'Every style needs setup — pattern, marker, fabric ordering, machine changeover, a sample round. Big factories spread that cost over huge runs, so small orders aren’t worth their time. Smaller, flexible factories are structured differently and can run 300–500 pieces per style economically.' },
      { type: 'h2', text: 'What MOQ to realistically expect' },
      { type: 'ul', items: [
        'Knit basics (tees, polos): from ~300 pieces per style/colour at a low-MOQ factory.',
        'Below ~100 pieces you’re usually into print-on-demand or local makers, at far higher unit cost.',
        'Fabric minimums can drive the real floor — using in-stock fabrics keeps MOQ low.',
      ] },
      { type: 'h2', text: 'How to keep your first order small' },
      { type: 'ul', items: [
        'Limit colours — MOQ is usually *per colour*, so 3 colours × 300 is 900 pieces.',
        'Use common fabrics the factory already stocks or buys in volume.',
        'Start with 1–2 hero styles, prove sell-through, then scale.',
        'Be clear about your growth plan — factories flex minimums for brands they expect to grow with.',
      ] },
      { type: 'h2', text: 'The landed-cost angle small brands miss' },
      { type: 'p', text: 'A low MOQ is worth little if duty eats your margin. Sourcing from an LDC like Nepal, your knit basics enter the EU, UK, and Canada duty-free — so a small, affordable run also lands cheaply. <a href="/why-nepal/">Here’s how that works.</a>' },
      { type: 'h2', text: 'Built for growing brands' },
      { type: 'p', text: 'We’re a small-batch-friendly factory — low minimums, flexible planning, and the attention a growing brand actually needs. Start small, scale as you sell. <a href="/products/">See our line</a> or <a href="/contact/">tell us what you’re launching</a>.' },
    ],
  },
  {
    slug: 'china-plus-one-apparel-nepal-second-sourcing',
    title: 'China Plus One for apparel: is Nepal your second sourcing country?',
    description:
      'Brands are diversifying apparel sourcing away from single-country risk. Here’s what "China Plus One" means for clothing, and why Nepal is a strong second source for knit basics.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['China plus one', 'Sourcing'],
    body: [
      { type: 'p', text: '“China Plus One” — keeping your main supply base but adding a second country to reduce risk — has moved from strategy deck to standard practice. Over 80% of US fashion brands now source from 10+ countries, and most plan to add more. If you’re building your “plus one” for knit basics, here’s why Nepal deserves a look.' },
      { type: 'h2', text: 'Why brands are diversifying now' },
      { type: 'ul', items: [
        'Tariff volatility — US tariffs on China have spiked, and rates shift with politics.',
        'Concentration risk — a single country (or factory) is a single point of failure.',
        'Buyer and investor pressure for resilient, transparent supply chains.',
      ] },
      { type: 'h2', text: 'What makes a good “plus one” for knit basics' },
      { type: 'p', text: 'You want a country with favourable duty access to your market, competitive cost, and factories that suit your order size. For tees, polos, and jersey, that points to LDC producers with duty-free access — where Nepal stands out.' },
      { type: 'h2', text: 'Why Nepal works as a second source' },
      { type: 'ul', items: [
        'Duty-free to the EU, UK, and Canada (LDC single-transformation rules — imported fabric qualifies).',
        'The lowest US tariff in South Asia — ~10%, vs ~50% India and ~20% Bangladesh in the current environment.',
        'Spare capacity and low MOQs — you get attention and flexibility, not a queue behind mega-buyers.',
        'Ethical, transparent production — a story your customers increasingly ask for.',
      ] },
      { type: 'h2', text: 'The honest trade-offs' },
      { type: 'p', text: 'Nepal is landlocked (bulk sea freight routes via Kolkata/Vizag), and the industry is smaller — it’s ideal for small-to-mid knit programs, not 100,000-piece single orders. For most brands diversifying their knit basics, that’s exactly the right fit.' },
      { type: 'p', text: 'Thinking about your plus-one? <a href="/why-nepal/">See the full Nepal sourcing case</a> or <a href="/contact/">start a conversation</a> — we’ll be honest about whether we’re the right fit.' },
    ],
  },
  {
    slug: 'cost-to-manufacture-a-t-shirt',
    title: 'What does it cost to manufacture a t-shirt? A cost breakdown for brands',
    description:
      'Where your per-shirt cost actually comes from — fabric, cutting, sewing, trims, finishing, and how duty affects your true landed cost when sourcing from Nepal.',
    date: '2026-07-13',
    readMins: 6,
    tags: ['Pricing', 'Sourcing'],
    body: [
      { type: 'p', text: '“How much does a t-shirt cost to make?” is the first question every brand asks — and the honest answer is “it depends,” because the price is built from parts. Understanding those parts helps you compare quotes fairly and spot where you can save.' },
      { type: 'h2', text: 'What goes into the per-piece cost' },
      { type: 'ul', items: [
        'Fabric — usually the biggest single component; driven by composition (cotton vs CVC), GSM (weight), and quantity.',
        'Cutting & sewing (the “CMT” — cut, make, trim) — labour to turn fabric into a garment.',
        'Trims — thread, labels, care labels, hangtags, packaging.',
        'Finishing & QC — pressing, folding, inspection, poly-bagging.',
        'Sampling & setup — amortised over the run (why low MOQ costs a bit more per piece).',
      ] },
      { type: 'h2', text: 'Why quotes vary so much' },
      { type: 'p', text: 'Two quotes for “a t-shirt” can differ 2–3× because of fabric weight and quality, order quantity (bigger runs = lower unit cost), country labour rates, and what’s included (are labels, tags, and packing in the price, or extra?). Always compare quotes at the same GSM, quantity, and inclusions.' },
      { type: 'h2', text: 'The number that actually matters: landed cost' },
      { type: 'p', text: 'Your real cost isn’t the factory price — it’s the <strong>landed cost</strong>: factory price + freight + import duty. This is where sourcing country matters enormously. A shirt made in Nepal enters the EU, UK, and Canada <strong>duty-free</strong>, versus ~12% duty from most countries — so a similar factory price lands cheaper. <a href="/why-nepal/">See the duty math.</a>' },
      { type: 'h2', text: 'Get a real number for your shirt' },
      { type: 'p', text: 'The only accurate cost is a quote against your actual spec. Send us your design or a reference and target quantity and we’ll break down fabric, CMT, trims, and landed cost. <a href="/contact/">Request a quote.</a>' },
    ],
  },
  {
    slug: 'what-is-a-tech-pack',
    title: 'What is a tech pack — and what your factory needs to quote your order',
    description:
      'A tech pack is the blueprint your manufacturer builds from. Here’s what goes in one, why it matters, and the minimum info a factory needs to quote your garment accurately.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['How to', 'Startups'],
    body: [
      { type: 'p', text: 'If a factory has asked you for a “tech pack” and you weren’t sure what they meant — you’re not alone. A tech pack is simply the technical blueprint of your garment. The better yours is, the more accurate your quote and the fewer surprises in production.' },
      { type: 'h2', text: 'What a tech pack contains' },
      { type: 'ul', items: [
        'A technical sketch (front/back) with construction details.',
        'Measurements / a size chart with grading across sizes.',
        'Fabric spec — composition and GSM (weight).',
        'Trims & labels — thread, buttons, care/brand labels, hangtags.',
        'Colours (ideally with Pantone references).',
        'Artwork / print / embroidery placement and files.',
        'Packaging requirements.',
      ] },
      { type: 'h2', text: 'Don’t have a tech pack yet? Start with this minimum' },
      { type: 'p', text: 'You don’t need a perfect tech pack to get started. To quote a knit garment, a good factory needs at least: the garment type, a reference sample or clear photos, your target fabric/GSM (or “advise me”), size range, quantities per style/colour, and your labelling needs. A capable manufacturer with in-house CAD can help develop the rest from there.' },
      { type: 'h2', text: 'Why it matters' },
      { type: 'p', text: 'A vague brief gets a vague quote — and mismatched expectations at sampling. A clear spec gets an accurate price, a faster sample, and a garment that matches what’s in your head.' },
      { type: 'h2', text: 'We’ll help you build it' },
      { type: 'p', text: 'With in-house Optitex CAD, we can develop patterns and specs from a sketch or reference — you don’t need everything perfect on day one. <a href="/contact/">Send us what you have</a> and we’ll take it from there.' },
    ],
  },
  {
    slug: 'private-label-vs-white-label-vs-oem-odm',
    title: 'Private label vs. white label vs. OEM vs. ODM: which do you actually need?',
    description:
      'These four terms confuse every new brand. Here’s what each manufacturing model means in plain English, and which fits your product and stage.',
    date: '2026-07-13',
    readMins: 4,
    tags: ['How to', 'Sourcing'],
    body: [
      { type: 'p', text: 'Sourcing conversations are full of jargon — private label, white label, OEM, ODM. They describe *how much of the product is yours vs. the factory’s*. Here’s each in plain English.' },
      { type: 'h2', text: 'The four models' },
      { type: 'ul', items: [
        'White label — a generic, ready-made product you put your label on. Fastest, least custom.',
        'Private label — the factory makes a product to *your* designs and spec, exclusively for your brand. Full control of design, fabric, fit.',
        'OEM (Original Equipment Manufacturer) — the factory manufactures to your design/spec (essentially private-label production).',
        'ODM (Original Design Manufacturer) — the factory designs *and* makes it; you brand and sell it. Fastest to market with less design work.',
      ] },
      { type: 'h2', text: 'Which fits you?' },
      { type: 'ul', items: [
        'Want it fast and simple, less differentiation → white label / ODM.',
        'Want your own designs, fabrics, and fits (a real brand) → private label / OEM.',
        'Short on time but want it “yours” → start with the factory’s proven designs (ODM), customise over time.',
      ] },
      { type: 'h2', text: 'We do both' },
      { type: 'p', text: 'We manufacture <strong>private label</strong> to your tech pack, and we also offer <strong>ready-made designs</strong> you can import and sell (ODM-style) for a fast, low-risk start. <a href="/products/">See both options.</a>' },
    ],
  },
  {
    slug: 'gsm-fabric-weight-guide-tshirts-polos',
    title: 'GSM explained: how to choose t-shirt and polo fabric weight',
    description:
      'GSM is the number that most affects how your garment feels and drapes. Here’s what GSM means and which weights work best for t-shirts, polos, and knit basics.',
    date: '2026-07-13',
    readMins: 4,
    tags: ['Fabric', 'How to'],
    body: [
      { type: 'p', text: 'When a factory asks what GSM you want, they’re asking how heavy your fabric should be — and it’s one of the biggest decisions for how your garment feels. Here’s a plain-English guide.' },
      { type: 'h2', text: 'What GSM means' },
      { type: 'p', text: 'GSM = grams per square metre — the fabric’s weight. Lower GSM = lighter, thinner, more breathable. Higher GSM = heavier, thicker, more premium-feeling and durable. It’s not “better or worse,” it’s fit-for-purpose.' },
      { type: 'h2', text: 'Rough GSM guide for knit basics' },
      { type: 'table', head: ['Garment', 'Typical GSM', 'Feel'], rows: [
        ['Lightweight tee', '140–160', 'Thin, breathable, summer'],
        ['Standard tee', '160–200', 'The everyday sweet spot'],
        ['Premium / heavyweight tee', '200–240+', 'Structured, boxy, premium'],
        ['Pique polo', '180–220', 'Classic polo body'],
      ] },
      { type: 'h2', text: 'How to choose' },
      { type: 'ul', items: [
        'Match your market — fashion/streetwear leans heavier (200+); basics and hot climates lean lighter.',
        'Heavier fabric costs more (more fibre) — balance feel against price.',
        'Always judge GSM on a physical sample, not a number on paper.',
      ] },
      { type: 'p', text: 'Not sure which weight suits your product? We’ll send samples across a GSM range so you can feel the difference. <a href="/contact/">Ask for samples.</a>' },
    ],
  },
  {
    slug: 'incoterms-apparel-imports-exw-fob-cif-nepal',
    title: 'Incoterms for apparel imports: EXW, FOB & CIF from Nepal explained',
    description:
      'Incoterms decide who pays for freight and who carries the risk at each stage. Here’s what EXW, FOB, and CIF mean for importing garments — and how landlocked Nepal ships.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['Logistics', 'How to'],
    body: [
      { type: 'p', text: 'A quote of “$3.20 EXW” and “$3.60 FOB” aren’t really different prices — they include different things. Incoterms define where the factory’s responsibility ends and yours begins. Getting them right avoids nasty surprises at the port.' },
      { type: 'h2', text: 'The three you’ll see most' },
      { type: 'ul', items: [
        'EXW (Ex Works) — you take the goods at the factory door and arrange everything after: inland transport, export, freight, import. Cheapest headline price, most work for you.',
        'FOB (Free On Board) — the factory delivers the goods, cleared for export, onto the vessel at the port. You handle sea freight and import. The most common apparel term.',
        'CIF (Cost, Insurance & Freight) — the factory arranges and pays sea freight + insurance to your destination port. You handle import clearance and delivery from there.',
      ] },
      { type: 'h2', text: 'How landlocked Nepal ships' },
      { type: 'p', text: 'Nepal has no seaport, so bulk sea freight routes overland to Indian ports (typically Kolkata/Haldia or Visakhapatnam) and sails from there — which is why you’ll often see “FOB Kolkata.” Air freight is available for samples and urgent runs. A good factory handles the export documentation and duty paperwork for you.' },
      { type: 'h2', text: 'Which should you quote?' },
      { type: 'p', text: 'If you’re new to importing, FOB or CIF keeps it simpler — the factory gets your goods onto the water. As you scale and get your own freight forwarder, EXW/FOB can save money. Tell us your destination and we’ll quote the term that suits you. <a href="/contact/">Get a quote.</a>' },
    ],
  },
  {
    slug: 'single-vs-double-transformation-rules-of-origin',
    title: 'Single vs. double transformation rules of origin, explained for apparel importers',
    description:
      'Rules of origin decide whether your garment qualifies for duty-free import. Here’s the difference between single and double transformation — and why it matters when the fabric is imported.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['Duty-free', 'How to'],
    body: [
      { type: 'p', text: 'Duty-free trade programs don’t just ask “where was it sewn?” — they ask “how much of it was actually made there?” That’s what rules of origin decide, and the single-vs-double transformation distinction is the whole game for apparel importers.' },
      { type: 'h2', text: 'What “transformation” means' },
      { type: 'p', text: 'A transformation is a substantial manufacturing step. For garments the two key steps are: (1) making the fabric (weaving/knitting yarn into cloth), and (2) making the garment (cutting and sewing cloth into a finished product).' },
      { type: 'h2', text: 'Single vs. double transformation' },
      { type: 'ul', items: [
        'Single transformation — cutting and sewing the garment in the country is enough to qualify as “made there,” even if the fabric is imported.',
        'Double transformation — both the fabric AND the garment must be made in the country (or qualifying region). Imported fabric disqualifies the garment.',
      ] },
      { type: 'h2', text: 'Why it matters if your fabric is imported' },
      { type: 'p', text: 'Many factories — in Nepal and elsewhere — import fabric (often from China) and cut/sew locally. Under <strong>single transformation</strong>, those garments still qualify as locally-made and get duty-free access. Under <strong>double transformation</strong>, they wouldn’t. Least Developed Countries like Nepal generally get single-transformation treatment in the EU, UK, and Canada — which is exactly why Nepal-made knitwear enters duty-free despite imported fabric.' },
      { type: 'quote', text: 'Always confirm the rule for your specific market and HS code — programs and rules change, and the difference between single and double transformation can be the difference between 0% and 12% duty.' },
      { type: 'p', text: 'Want to know if your product qualifies from Nepal? <a href="/why-nepal/">See our duty-free breakdown</a> or <a href="/contact/">tell us your market</a>.' },
    ],
  },
  {
    slug: 'nepal-ldc-graduation-2026-what-importers-must-know',
    title: 'Nepal LDC graduation 2026: what apparel importers need to know',
    description:
      'Nepal is scheduled to graduate from Least Developed Country status in November 2026. Here’s what that means for duty-free garment sourcing — and the window to plan around.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['Duty-free', 'Sourcing'],
    body: [
      { type: 'p', text: 'If you source — or are considering sourcing — garments from Nepal, one date matters: Nepal is scheduled to graduate from Least Developed Country (LDC) status in November 2026. Here’s what changes, what doesn’t, and why there’s a window worth planning around.' },
      { type: 'h2', text: 'Why LDC status matters' },
      { type: 'p', text: 'Nepal’s duty-free access to the EU (Everything But Arms), UK (DCTS), and Canada (LDCT) flows from its LDC status — and, crucially, LDCs get lenient “single transformation” rules, so imported fabric still qualifies. Graduation changes the framework these preferences sit in.' },
      { type: 'h2', text: 'The transition window' },
      { type: 'p', text: 'Graduation isn’t a cliff. The EU and UK grant a transition period that keeps duty-free access to roughly 2029. After that, access is expected to move to standard GSP schemes — which typically apply stricter “double transformation” rules of origin, under which imported fabric may no longer qualify.' },
      { type: 'h2', text: 'What importers should do' },
      { type: 'ul', items: [
        'Lock in duty-free EU/UK/Canada sourcing during the current window.',
        'Plan ahead for the post-transition rules — discuss fabric-sourcing options with your factory.',
        'Treat this as a reason to *start* a Nepal program now, not to avoid one.',
        'Always verify the current rule for your product and market before shipping.',
      ] },
      { type: 'p', text: 'We help buyers make the most of the current window and plan for the transition. <a href="/why-nepal/">See the duty-free details</a> or <a href="/contact/">talk to us about your program</a>.' },
    ],
  },
  {
    slug: 'how-to-start-a-clothing-brand-first-production-run',
    title: 'How to start a clothing brand: from idea to your first production run',
    description:
      'A practical roadmap for turning a clothing idea into real, sellable product — designs, tech packs, finding a manufacturer, MOQ, samples, and your first order.',
    date: '2026-07-13',
    readMins: 7,
    tags: ['Startups', 'How to'],
    body: [
      { type: 'p', text: 'Turning “I want to start a clothing brand” into boxes of real product on your doorstep follows a fairly predictable path. Here’s the roadmap, with the manufacturing steps most guides gloss over.' },
      { type: 'h2', text: '1. Nail the concept and designs' },
      { type: 'p', text: 'Decide what you’re making and for whom. Start narrow — one or two hero styles beat a sprawling range you can’t afford to produce. Sketches or reference garments are enough to begin.' },
      { type: 'h2', text: '2. Turn designs into a spec (tech pack)' },
      { type: 'p', text: 'A factory builds from a tech pack — sketch, measurements, fabric/GSM, trims, colours, artwork. You don’t need it perfect; a manufacturer with in-house CAD can help develop it from a reference.' },
      { type: 'h2', text: '3. Find the right manufacturer' },
      { type: 'p', text: 'Match the factory to your size. Big factories want big minimums; for a first run of a few hundred pieces you want a low-MOQ, small-batch-friendly factory. Vet them carefully — samples, video tour, references (see our guide on vetting a factory).' },
      { type: 'h2', text: '4. Sample, then produce' },
      { type: 'p', text: 'Get a pre-production sample and approve fit, fabric, and finish before bulk. Then your approved sample goes to the floor for your first run. Expect sampling in a couple of weeks and bulk in a few weeks after approval.' },
      { type: 'h2', text: '5. Think landed cost, not just unit price' },
      { type: 'p', text: 'Where you make it affects your true cost. Sourcing knit basics from an LDC like Nepal means duty-free import to the EU/UK/Canada — a real margin advantage for a young brand. <a href="/why-nepal/">Here’s how.</a>' },
      { type: 'p', text: 'Ready to make your first run? We’re built for exactly this — low MOQ, in-house CAD, honest guidance. <a href="/contact/">Tell us what you’re launching.</a>' },
    ],
  },
  {
    slug: 'sample-to-bulk-what-to-expect-first-order',
    title: 'Sample to bulk: what to expect on your first clothing production order',
    description:
      'The step-by-step of a garment order — from tech pack to sample approval to bulk production, QC, and shipping — so you know what happens and when.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['How to', 'Startups'],
    body: [
      { type: 'p', text: 'A first production order can feel like a black box. It isn’t — good factories follow a clear sequence. Knowing it helps you plan timelines and spot a disorganised supplier.' },
      { type: 'h2', text: 'The typical order flow' },
      { type: 'ul', items: [
        '1. Consultation & quote — you share designs/tech pack + quantities; the factory quotes MOQ, price, lead time.',
        '2. Sampling — the factory makes a pre-production sample to your spec (typically ~1–2 weeks for knits).',
        '3. Sample approval — you review fit, fabric, and finish; revise until it’s right. Nothing goes to bulk until you sign off.',
        '4. Bulk production — the approved sample goes to the floor; cut, sew, finish (typically ~4–6 weeks for knit basics).',
        '5. QC — in-line and final inspection for stitch quality, measurements, finish.',
        '6. Delivery — retail-ready packing, export docs, and shipping by sea or air.',
      ] },
      { type: 'h2', text: 'Where timelines slip (and how to avoid it)' },
      { type: 'ul', items: [
        'Slow sample approvals — respond quickly to keep momentum.',
        'Vague tech packs — the clearer your spec, the fewer sample rounds.',
        'Fabric lead time — using in-stock fabric shortens the whole cycle.',
      ] },
      { type: 'p', text: 'We keep you updated at every stage — photos and status so you always know where your order stands. <a href="/contact/">Start your first order.</a>' },
    ],
  },
  {
    slug: 'ethical-garment-manufacturing-questions-to-ask',
    title: 'Ethical garment manufacturing: the questions to ask any factory',
    description:
      'Sustainability and ethics are now buyer requirements, not nice-to-haves. Here are the questions that separate genuinely responsible factories from greenwashing.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['Ethics', 'Sourcing'],
    body: [
      { type: 'p', text: 'Your customers increasingly ask where and how their clothes are made — so you need to ask your factory. Here are the questions that cut through vague “we’re sustainable” claims to what’s actually true.' },
      { type: 'h2', text: 'On labour and conditions' },
      { type: 'ul', items: [
        'Do you pay at or above the legal minimum wage, on time?',
        'What are working hours and overtime policies?',
        'Do you have a strict no-child-labour policy?',
        'Can I visit, or see a live video of the floor?',
      ] },
      { type: 'h2', text: 'On compliance and audits' },
      { type: 'ul', items: [
        'What certifications or audits do you hold (BSCI, Sedex/SMETA, WRAP, SA8000)?',
        'If none yet — what’s your roadmap and timeline? (Honesty here is a good sign.)',
        'Are you a registered exporter with proper documentation?',
      ] },
      { type: 'h2', text: 'On environment' },
      { type: 'ul', items: [
        'What energy powers the factory? (Nepal’s grid is largely hydro-electric — a genuine plus.)',
        'How do you handle fabric waste and offcuts?',
      ] },
      { type: 'h2', text: 'The tell: honesty over badges' },
      { type: 'p', text: 'A factory that says “we’re fully certified in everything” without proof is a red flag. One that tells you plainly what it holds today and what’s in progress is usually more trustworthy. We take the honest route — <a href="/capabilities/">here’s our real compliance posture</a>, and you’re welcome to audit us.' },
    ],
  },
  {
    slug: 'cotton-cvc-poly-cotton-tshirt-fabric-blends',
    title: 'Cotton vs. CVC vs. poly-cotton: which blend for your t-shirt?',
    description:
      'The fabric blend changes your tee’s feel, price, durability, and print results. Here’s a plain guide to 100% cotton, CVC, and poly-cotton for brand owners.',
    date: '2026-07-13',
    readMins: 4,
    tags: ['Fabric', 'How to'],
    body: [
      { type: 'p', text: 'After weight (GSM), the biggest fabric decision for a tee is the blend. Here’s how the three common options compare — feel, cost, durability, and how they take print.' },
      { type: 'h2', text: 'The three main blends' },
      { type: 'ul', items: [
        '100% cotton — softest, most breathable, most natural feel; premium positioning. Shrinks a little; costs more.',
        'CVC (Chief Value Cotton, ~60/40 cotton/poly) — mostly-cotton feel with better durability and less shrinkage; a popular middle ground.',
        'Poly-cotton (e.g. 50/50 or 65/35) — most durable and cheapest, dries fast, holds shape; slightly less breathable, more synthetic feel.',
      ] },
      { type: 'h2', text: 'How to choose' },
      { type: 'ul', items: [
        'Premium/fashion brand → 100% cotton (often combed/ring-spun for extra softness).',
        'Value or workwear/uniform → poly-cotton or CVC for durability and cost.',
        'All-rounder → CVC balances feel, price, and longevity.',
        'Printing lots of DTG → cotton takes water-based/DTG print best; heavy poly suits screen/plastisol.',
      ] },
      { type: 'p', text: 'Not sure? We’ll send samples in a few blends so you can feel and test-print them. <a href="/contact/">Ask for fabric samples.</a>' },
    ],
  },
  {
    slug: 'how-to-reduce-apparel-import-duty-legally',
    title: 'How to legally reduce your apparel import duty',
    description:
      'Import duty can be 10–30% of your cost. Here are the legitimate ways brands lower it — trade preferences, sourcing country, rules of origin, and correct classification.',
    date: '2026-07-13',
    readMins: 6,
    tags: ['Duty-free', 'Pricing'],
    body: [
      { type: 'p', text: 'Import duty is often the most overlooked line in a brand’s cost — and one of the most controllable. On apparel it can run anywhere from ~10% to 30%+ depending on where you make it. Here are the legitimate levers to lower it.' },
      { type: 'h2', text: '1. Source from a duty-free / preferential country' },
      { type: 'p', text: 'The single biggest lever. Many markets grant duty-free access to garments from Least Developed Countries — e.g. the EU (EBA), UK (DCTS), and Canada (LDCT). A knit tee from Nepal enters those markets at 0% duty, versus ~12% from most countries. Choosing the sourcing country *is* duty strategy.' },
      { type: 'h2', text: '2. Understand rules of origin' },
      { type: 'p', text: 'Duty-free access depends on qualifying under rules of origin. LDCs typically get lenient “single transformation” — so a garment cut and sewn there qualifies even with imported fabric. Know the rule for your market before you commit.' },
      { type: 'h2', text: '3. Classify your product correctly' },
      { type: 'p', text: 'Duty rates vary by HS code. Small construction or composition differences can shift the classification (and the rate). Work with a customs broker to make sure you’re not overpaying on a mis-classification.' },
      { type: 'h2', text: '4. Keep your paperwork clean' },
      { type: 'p', text: 'Preferential rates require documentation — a valid Certificate of Origin (e.g. via REX for the EU). A good factory supplies this; without it, you pay full duty regardless of eligibility.' },
      { type: 'quote', text: 'This is about using trade programs as intended — not dodging duty. Sourcing country + correct rules of origin + clean paperwork is where the legitimate savings are.' },
      { type: 'p', text: 'We supply the Certificate of Origin and help you source where the duty works in your favour. <a href="/why-nepal/">See the duty-free markets</a> or <a href="/contact/">tell us your destination</a>.' },
    ],
  },
  {
    slug: 'first-time-importer-guide-working-with-garment-factory',
    title: 'A first-time importer’s guide to working with a garment factory',
    description:
      'New to importing garments? Here’s how to communicate with an overseas factory, what MOQ / lead time / payment terms to expect, and how to avoid the common first-timer mistakes.',
    date: '2026-07-13',
    readMins: 6,
    tags: ['How to', 'Startups'],
    body: [
      { type: 'p', text: 'Working with an overseas factory for the first time is smoother than it looks — if you know the norms. Here’s what to expect and how to be the kind of buyer factories prioritise.' },
      { type: 'h2', text: 'What to expect on terms' },
      { type: 'ul', items: [
        'MOQ — minimum order per style/colour. Low-MOQ factories start around a few hundred pieces.',
        'Lead time — sampling first (often 1–2 weeks), then bulk (often 4–6 weeks) after approval.',
        'Payment — commonly a deposit to start and balance against shipping/inspection; L/C for larger orders. Avoid 100% upfront to a stranger.',
        'Incoterms — EXW/FOB/CIF decide who handles freight (see our Incoterms guide).',
      ] },
      { type: 'h2', text: 'How to communicate well' },
      { type: 'ul', items: [
        'Be specific — send a tech pack or clear reference, quantities, and target price.',
        'Respond quickly — factories prioritise responsive buyers.',
        'Confirm details in writing — spec, price, dates, terms.',
        'Approve a sample before bulk — always.',
      ] },
      { type: 'h2', text: 'Common first-timer mistakes' },
      { type: 'ul', items: [
        'Skipping the sample to “save time” — the costliest mistake.',
        'Ordering too many styles/colours at once (MOQ stacks up fast).',
        'Ignoring landed cost — duty and freight can dwarf a small unit-price difference.',
        'Not vetting the factory (see our guide on avoiding scams).',
      ] },
      { type: 'p', text: 'We’re used to guiding first-time importers — clear communication, honest terms, and help at every step. <a href="/contact/">Start with a conversation.</a>' },
    ],
  },
  {
    slug: 'screen-print-vs-dtg-vs-embroidery-apparel',
    title: 'Screen print vs. DTG vs. embroidery: decorating your apparel',
    description:
      'The three main ways to brand a garment — screen printing, DTG, and embroidery — compared on cost, quantity, detail, and durability, so you pick the right one.',
    date: '2026-07-13',
    readMins: 5,
    tags: ['How to', 'Fabric'],
    body: [
      { type: 'p', text: 'How you put your logo or artwork on a garment affects cost, look, and durability. The three main methods each win in different situations — here’s how to choose.' },
      { type: 'h2', text: 'Screen printing' },
      { type: 'p', text: 'Ink pushed through a stencil, one screen per colour. Best for bold designs with few colours at higher quantities — durable and cheap per piece at scale. Setup cost per colour makes it less suited to tiny runs or photo-realistic art.' },
      { type: 'h2', text: 'DTG (direct-to-garment)' },
      { type: 'p', text: 'A printer sprays ink straight onto the fabric, like an inkjet. Best for detailed, full-colour, or photographic designs and low quantities (no per-colour setup). Works best on cotton; print can feel softer but may be less durable than screen over many washes.' },
      { type: 'h2', text: 'Embroidery' },
      { type: 'p', text: 'Thread stitched into the fabric. The most premium, durable, and tactile — ideal for logos on polos, caps, and workwear. Priced by stitch count; not suited to large or highly detailed artwork.' },
      { type: 'h2', text: 'Quick guide' },
      { type: 'ul', items: [
        'Bold logo, big run → screen print.',
        'Detailed/photo art, small run → DTG.',
        'Premium logo on polos/uniforms → embroidery.',
      ] },
      { type: 'p', text: 'We can advise the best decoration for your program and coordinate it alongside your garment production. <a href="/contact/">Tell us your artwork and quantities.</a>' },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug);
}
